server:
  port: ${PORT:8888}

eureka:
  instance:
    preferIpAddress: false
    nonSecurePort: ${PORT:8888}
    hostname: ${DOMAIN:localhost}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:localhost:8761}/eureka/